dist: trusty
sudo: required
language: ruby
rvm: 2.2.3
bundler_args: --without development production

env:
  - ES_VERSION=2.4.5 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz  TEST_CLUSTER_COMMAND=/tmp/elasticsearch-2.4.3/bin/elasticsearch

before_install:
  - curl -sS https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.3/elasticsearch-2.4.3.tar.gz | tar xz -C /tmp

before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate RAILS_ENV=test
  - export RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
  - export RECAPTCHA_SITE_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  - sleep 10 # To make sure Elasticsearch instance is ready

script:
  - bundle exec rspec spec/
  - bundle exec rake test
