sudo: required
language: ruby
rvm:
- 2.2.3
bundler_args: --without development production

services:
  - elasticsearch

# env:
#   - ES_VERSION=2.4.5 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.5/elasticsearch-2.4.5.tar.gz && sudo dpkg -i --force-confnew elasticsearch-2.4.5.tar.gz && sudo service elasticsearch restart
  # - wget ${ES_DOWNLOAD_URL}
  # - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  # - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &

before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create db:migrate RAILS_ENV=test
- export RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
- export RECAPTCHA_SITE_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
- sleep 10 # To make sure Elasticsearch instance is ready

script:
# - curl -X GET http://localhost:9250/
# - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
# - travis_debug
- bundle exec rspec spec/
- bundle exec rake test
